// Generated by Firebase.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn8yqpcXvfKdR23O0fWBthGlqyGGbUyl0',
    appId: '1:859154221248:android:8220ebf4b81b661f908525',
    messagingSenderId: '859154221248',
    projectId: 'meetcafe-57f3a',
    storageBucket: 'meetcafe-57f3a.firebasestorage.app',
  );
}

